not all the required values are stored in constants right now
[martin@gpd cl-gen-cuda-try]$ gcc -Wall -Wextra -std=c11 -g -O3 -march=native -mfma -ffast-math source/simd_try.c -o source/simd_try_gcc -lm  2>&1 > source/simd_try_gcc.out
source/simd_try.c: In function 'simd_16_fft_112_16_7':
source/simd_try.c:171:40: error: 'w13879754_m73_1' undeclared (first use in this function); did you mean 'w8388608_m23_1'?
                                        w13879754_m73_1,
                                        ^~~~~~~~~~~~~~~
                                        w8388608_m23_1
source/simd_try.c:171:40: note: each undeclared identifier is reported only once for each function it appears in
source/simd_try.c:212:40: error: 'w9253170_m72_1' undeclared (first use in this function)
                                        w9253170_m72_1,
                                        ^~~~~~~~~~~~~~
source/simd_try.c:246:40: error: 'w11566462_m73_1' undeclared (first use in this function); did you mean 'w16356576_m24_1'?
                                        w11566462_m73_1,
                                        ^~~~~~~~~~~~~~~
                                        w16356576_m24_1
source/simd_try.c:253:40: error: 'w11566462_m72_1' undeclared (first use in this function); did you mean 'w16356576_m24_1'?
                                        w11566462_m72_1,
                                        ^~~~~~~~~~~~~~~
                                        w16356576_m24_1
source/simd_try.c:294:40: error: 'w13879754_m72_1' undeclared (first use in this function); did you mean 'w13116956_m24_1'?
                                        w13879754_m72_1,
                                        ^~~~~~~~~~~~~~~
                                        w13116956_m24_1
source/simd_try.c:30:28: warning: variable 'x1_im' set but not used [-Wunused-but-set-variable]
     static alignas(64) vsf x1_im[7];
                            ^~~~~
source/simd_try.c: In function 'main':
source/simd_try.c:329:11: warning: unused variable 'a' [-Wunused-variable]
     float a = 0x1.99999Ap-4;
           ^